config/routes.rb
Rails.application.routes.draw do
  resources :places

  root 'places#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, :if => :latitude_changed?

  validates :title, presence: true

  def latlng
    [latitude, longitude]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    if params[:search]
      @places = Place.near(params[:search], 5)
      @has_distance = true
    else
      @places = Place.all
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :address, :phone, :website, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MappingHisarustu</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

  <!-- Mobile meta tags-->
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="MobileOptimized" content="320"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="cleartype" content="on">

  <script type="text/javascript">
    window.cloudmade_api_key = '<%= Rails.application.secrets.cloudmade_api_key %>';
  </script>
</head>
<body>

  <div id="sidebar">
    <div class="sidebar_header">
      <h3><%= link_to "Mapping Hisarustu", root_path %></h3>
    </div>
  

    <div class="sidebar_content">
        <%= form_tag places_path, :method => :get, class: "form-inline" do %>
          <input type="text" name="search" class="form-control" placeholder="Search place, location etc." />
          <select class="form-control span2">
              <option value="one">Label</option>
              <option value="two">Restaurant</option>
              <option value="three">Library</option>
              <option value="four">Shop</option>
              <option value="five">Bookstore</option>
          </select>
          <%= submit_tag "Find", class: 'form-control btn' %>
        <% end %>
      <hr>
      <div class='text-left'>
        <%= yield %>
      </div>
    </div>
  </div>

  <div class="toggle_description btn" type="button">
    &larr; About this map
  </div>

  <div class="description_box">
    <div class="x_button toggle_description btn btn-primary" type="button">
      <strong>X</strong>
    </div>
    <div class="description_box_header"></div>
    <div class="description_box_content">
      <div class="description_box_text"></div>
      <div id="caption_box"></div>
    </div>
  </div>
  <div class="description_box_cover"></div>
  
  <div id="map"></div>

</body>
</html>

app/views/places/_form.html.erb
<h4>Add New Place</h4>
<%= form_for @place, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls ">
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :address, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :address, rows: 3, placeholder: 'automatically loaded when you select a point' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :phone, class: "control-label" %>
    <div class="controls ">
      <%= f.text_field :phone, placeholder: "Phone" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :website, class: "control-label" %>
    <div class="controls ">
      <%= f.text_field :website, placeholder: "Website" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :latitude, class: "control-label" %>
    <div class="controls ">
      <%= f.text_field :latitude, readonly: true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :longitude, class: "control-label" %>
    <div class="controls ">
      <%= f.text_field :longitude, readonly: true %>
    </div>
  </div>


  <div class="control-group">
    <div class="controls">
      <button type="" class="btn btn-danger">Reset</button>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    var popup = L.popup();
    var temp_marker = new L.Marker;

    function onMapClick(e) {
      window.map.removeLayer(temp_marker);
      // popup
      //     .setLatLng(e.latlng)
      //     .setContent("You clicked the map at " + e.latlng.lat.toString() + "," + e.latlng.lng.toString())
      //     .openOn(window.map);
       // L.marker(e.latlng).addTo(map);
      temp_marker = new L.Marker(e.latlng, {draggable:true});
      window.map.addLayer(temp_marker);
      $("input#place_latitude").val(e.latlng.lat.toString());
      $("input#place_longitude").val(e.latlng.lng.toString());
    }

    window.map.on('click', onMapClick);
  })
</script>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<table class='table table-hover'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <% if @has_distance %>
      <th>Distance</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.title, place %></td>
        <td><%= place.address %></td>
        <% if @has_distance %>
        <td><%= place.distance.to_i %> km</td>
        <% end %>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
        <script>
          $(document).ready(function(){
            var latlng = ['<%= place.latitude %>', '<%= place.longitude %>'];
            var marker = L.marker(latlng);
            marker.bindPopup('<%= place.title %>' + '<br/>' + '<%= place.address %>');
            marker.addTo(window.map);
          })
        </script>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<!-- <h1>New place</h1> -->

<%= render 'form' %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @place.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @place.website %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

<script>
  $(document).ready(function(){
    var latlng = ['<%= @place.latitude %>', '<%= @place.longitude %>'];
    var marker = L.marker(latlng);
    marker.bindPopup('<%= @place.title %>' + '<br/>' + '<%= @place.address %>');
    marker.addTo(window.map);
  })
</script>